-- Envuelve funciones de rol y auth.uid() en (select …) para que se evalúen una vez por consulta (initplan) y no por fila.
-- Lógica idéntica: verificado en 7 perfiles (admin, coach, recepción, nutricionista, 2 socios, sin sesión), 641 chequeos, 0 diferencias.
-- Aplicada en producción (siecbdatfgmqbpxqtvsl) el 8-oct-2026.
alter policy blq_escribir on public.bloques using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy blq_leer on public.bloques using (((select public.es_staff()) OR (mi_sesion(sesion_id) AND ( SELECT koach_gate() AS koach_gate))));
alter policy apoyo_escribir on public.sesiones_extra using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy apoyo_leer on public.sesiones_extra using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy nut_socio on public.evaluaciones_nutricion using ((socio_id = (select auth.uid())));
alter policy nut_staff on public.evaluaciones_nutricion using (((select public.koach_rol()) = ANY (ARRAY['admin'::text, 'nutricionista'::text]))) with check (((select public.koach_rol()) = ANY (ARRAY['admin'::text, 'nutricionista'::text])));
alter policy planes_escribir on public.planes using ((select public.es_admin())) with check ((select public.es_admin()));
alter policy modl_staff on public.modificaciones_legacy using ((select public.es_staff()));
alter policy solo_admin on public.ia_log using ((select public.es_admin())) with check ((select public.es_admin()));
alter policy set_leer on public.set_registros using (((select public.es_staff()) OR mi_registro(registro_id)));
alter policy set_staff on public.set_registros using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy aj_leer on public.koach_ajustes using (((select auth.uid()) IS NOT NULL));
alter policy reg_leer on public.sesiones_registro using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy reg_socio_crear on public.sesiones_registro with check ((socio_id = (select auth.uid())));
alter policy reg_socio_editar on public.sesiones_registro using ((socio_id = (select auth.uid()))) with check ((socio_id = (select auth.uid())));
alter policy reg_staff on public.sesiones_registro using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy sol_leer on public.solicitudes using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy sol_socio on public.solicitudes with check (((socio_id = (select auth.uid())) AND (estado = 'pendiente'::text)));
alter policy sol_staff on public.solicitudes using ((select public.es_staff())) with check ((select public.es_staff()));
alter policy val_staff on public.validaciones using ((select public.es_staff())) with check ((select public.es_staff()));
alter policy asig_escribir on public.asignaciones using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy asig_leer on public.asignaciones using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy be_escribir on public.bloque_ejercicios using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy be_leer on public.bloque_ejercicios using (((select public.es_staff()) OR (mi_bloque(bloque_id) AND ( SELECT koach_gate() AS koach_gate))));
alter policy cong_escribir on public.membresia_congelamientos using ((select public.es_comercial())) with check ((select public.es_comercial()));
alter policy cong_leer on public.membresia_congelamientos using (((select public.es_comercial()) OR mi_membresia(membresia_id)));
alter policy objetivos_escribir on public.volumen_objetivos using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy objetivos_leer on public.volumen_objetivos using (((select public.es_staff()) OR (mi_protocolo(protocolo_id) AND ( SELECT koach_gate() AS koach_gate))));
alter policy cargas_leer on public.cargas using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy cargas_socio on public.cargas with check ((socio_id = (select auth.uid())));
alter policy cargas_staff on public.cargas using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy dx_escribir on public.designaciones_extra using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy dx_leer on public.designaciones_extra using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy dx_socio on public.designaciones_extra using ((socio_id = (select auth.uid()))) with check ((socio_id = (select auth.uid())));
alter policy apoyo_escribir on public.planes_semanales using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy apoyo_leer on public.planes_semanales using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy pag_escribir on public.pagos using ((select public.es_comercial())) with check ((select public.es_comercial()));
alter policy pag_leer on public.pagos using (((select public.es_comercial()) OR (socio_id = (select auth.uid()))));
alter policy ss_leer on public.sesion_suspendida using (((socio_id = (select auth.uid())) OR (select public.es_entrenador())));
alter policy catalogo_escribir on public.coach_config using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy solo_admin on public.wa_messages using ((select public.es_admin())) with check ((select public.es_admin()));
alter policy solo_admin on public.wa_conversations using ((select public.es_admin())) with check ((select public.es_admin()));
alter policy perfil_borrar on public.profiles using ((select public.es_admin()));
alter policy perfil_crear on public.profiles with check ((((id = (select auth.uid())) AND (role = 'socio'::user_role)) OR ((select public.es_staff()) AND (role = 'socio'::user_role)) OR (select public.es_admin())));
alter policy perfil_editar on public.profiles using (((id = (select auth.uid())) OR (select public.es_staff()))) with check (((id = (select auth.uid())) OR (select public.es_staff())));
alter policy perfil_leer on public.profiles using (((id = (select auth.uid())) OR (select public.es_staff())));
alter policy apoyo_escribir on public.modificaciones using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy apoyo_leer on public.modificaciones using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy proto_escribir on public.protocolos using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy proto_leer on public.protocolos using (((select public.es_staff()) OR ((socio_id = (select auth.uid())) AND ( SELECT koach_gate() AS koach_gate))));
alter policy ses_escribir on public.sesiones_protocolo using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy ses_leer on public.sesiones_protocolo using (((select public.es_staff()) OR (mi_sesion(id) AND ( SELECT koach_gate() AS koach_gate))));
alter policy apoyo_escribir on public.saltos using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy apoyo_leer on public.saltos using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy apoyo_escribir on public.semanas_socio using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy apoyo_leer on public.semanas_socio using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy alerta_leer on public.membresia_alertas using (((select public.es_comercial()) OR mi_membresia(membresia_id)));
alter policy ev_crear on public.admin_eventos with check ((select public.es_staff()));
alter policy ev_leer on public.admin_eventos using ((select public.es_comercial()));
alter policy ci_leer on public.check_ins using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
alter policy ci_staff on public.check_ins using ((select public.es_staff())) with check ((select public.es_staff()));
alter policy catalogo_escribir on public.ejercicios using ((select public.es_entrenador())) with check ((select public.es_entrenador()));
alter policy mem_escribir on public.membresias using ((select public.es_comercial())) with check ((select public.es_comercial()));
alter policy mem_leer on public.membresias using (((select public.es_comercial()) OR (socio_id = (select auth.uid()))));
alter policy sh_leer on public.sesion_habilitada using (((socio_id = (select auth.uid())) OR (select public.es_entrenador())));
alter policy pr_leer on public.acceso_prorrogas using (((select public.es_staff()) OR (socio_id = (select auth.uid()))));
